### ISSUE TITLE
Encounter Error when upload test result to server

### ISSUE THREAD

**Issue by BUAADreamer** [Cuberick-Orion/CIRR#13] opened 2023-03-14 02:29 UTC
![image](https://user-images.githubusercontent.com/64362896/224877260-a33db9be-c063-4e64-97b7-7e5774d54c72.png)

**Comment by onevae** [comment] 2023-04-17 09:06
me too. How did you deal with it?

**Comment by onevae** [comment] 2023-04-17 09:12
ok! Thanks!!

**Comment by Cuberick-Orion** [comment] 2024-03-10 06:37
Duplicate of #15

**Closed by Cuberick-Orion** 2024-03-10 06:37 UTC
